### ISSUE TITLE
Error in C function svg: Expected  just one argument on line 59 of scss/apnscp/_ajax.scss

### ISSUE THREAD

**Issue by hachiweb** [apisnetworks/apiscp-bootstrap-sdk#14]
Hi developer(s),
I am getting an issue running grunt command, please check the screenshot attached.
Thanks
![image - 2021-04-19T150742 030](https://user-images.githubusercontent.com/33425893/115215770-72fb5a00-a121-11eb-9201-e601624311c8.png)

**Comment by anatolinicolae** [comment]
Issue need more info:
- what's the environment?
- anything edited in the theme already? if yes, did it work before?
- why is he running grunt alone? docs say grunt watch or grunt dist
https://github.com/apisnetworks/apiscp-bootstrap-sdk#getting-started

**Comment by hachiweb** [comment]
Hey, thanks for the response

**Comment by hachiweb** [comment]
Getting same error of  grunt dist

**Comment by hachiweb** [comment]
Environment is Ubuntu 20.04, have not made any changes. 
Why the grunt dist is throwing the same error. 
Am I missing something? 

Any help will be appreciated

**Comment by anatolinicolae** [comment]
What's your Node version? Recommended one is 6.10, you can try installing that via nvm and see how that works out. Make sure to reinstall modules with that version.

**Comment by hachiweb** [comment]
Hello, I am using 15, latest one.

**Comment by msaladna** [comment]
v12 is required per [package.json](https://github.com/apisnetworks/apiscp-bootstrap-sdk/blob/master/package.json#L69). It's a change in the node-sass bindings installed on v14+

**Comment by hachiweb** [comment]
> v12 is required per [package.json](https://github.com/apisnetworks/apiscp-bootstrap-sdk/blob/master/package.json#L69). It's a change in the node-sass bindings installed on v14+

So, I should downgrade to v12?

**Comment by msaladna** [comment]
Yes. [nvm](https://github.com/nvm-sh/nvm) is what I recommend to manage multiple Nodes.
